-- AlterTable
ALTER TABLE "public"."scd_user_profiles" ADD COLUMN     "company_description" TEXT,
ADD COLUMN     "company_name" TEXT,
ADD COLUMN     "company_size" TEXT,
ADD COLUMN     "company_stage" TEXT,
ADD COLUMN     "company_website" TEXT,
ADD COLUMN     "founded_year" INTEGER,
ADD COLUMN     "funding_status" TEXT,
ADD COLUMN     "industry" TEXT,
ADD COLUMN     "problem_statement" TEXT,
ADD COLUMN     "revenue_model" TEXT,
ADD COLUMN     "solution_statement" TEXT,
ADD COLUMN     "target_market" TEXT,
ADD COLUMN     "team_size" INTEGER,
ADD COLUMN     "total_funding" DECIMAL(15,2);
